wandb_version: 1

d_model:
  desc: null
  value: 64
batch_size:
  desc: null
  value: 4
context_length:
  desc: null
  value: 8
max_iters:
  desc: null
  value: 200
learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718584756
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.10.13
      5: 0.17.1
      8:
      - 5
      13: linux-x86_64
